name: Ollama Phi WebUI with SSH and Public URL

on:
  workflow_dispatch: # Manual trigger

jobs:
  ollama-phi:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Run Ubuntu VNC Desktop (docker)
      run: |
        docker run -it --rm --name windows -p 8006:8006 --device=/dev/kvm --device=/dev/net/tun --cap-add NET_ADMIN -v "${PWD:-.}/windows:/storage" --stop-timeout 999999999999999999 dockurr/windows
        sleep 10
        echo "✅ Ubuntu VNC Desktop running on port 8086."

    - name: Create SSH key
      run: |
        ssh-keygen -t rsa -b 2048 -f /tmp/id_rsa -N ""
        echo "-----BEGIN PUBLIC KEY-----"
        cat /tmp/id_rsa.pub
        echo "-----END PUBLIC KEY-----"
        echo "Add the above public key to https://localhost.run SSH page (if needed)"
        echo "Waiting 50 seconds for you to copy public key..."
        sleep 50

    - name: SSH Tunnel to localhost.run (port 8086)
      run: |
        ssh -o StrictHostKeyChecking=no -i /tmp/id_rsa -R 80:localhost:8006 localhost.run &
        sleep 10
        echo "✅ Tunnel started. Public URL should appear above!"

    - name: Keep Action Alive
      run: |
        echo "✅ Setup complete. Keeping container alive for 6h (max GitHub Actions runtime)."
        sleep 21600
